mev_boost_container_image: "{{ default_tooling_images.mev_boost }}"

mev_boost_container_env:
  GENESIS_TIMESTAMP: "{{ (lookup('ansible.builtin.file', eth_testnet_config_local_dir_src + 'config.yaml') | from_yaml).MIN_GENESIS_TIME + (lookup('ansible.builtin.file', eth_testnet_config_local_dir_src + 'config.yaml') | from_yaml).GENESIS_DELAY }}"
  GENESIS_FORK_VERSION: "0x10{{ ethereum_genesis_fork_version_suffix }}"
  ALTAIR_FORK_VERSION: "0x20{{ ethereum_genesis_fork_version_suffix }}"
  BELLATRIX_FORK_VERSION: "0x30{{ ethereum_genesis_fork_version_suffix }}"
  CAPELLA_FORK_VERSION: "0x40{{ ethereum_genesis_fork_version_suffix }}"
  DENEB_FORK_VERSION: "0x50{{ ethereum_genesis_fork_version_suffix }}"
  ELECTRA_FORK_VERSION: "0x60{{ ethereum_genesis_fork_version_suffix }}"
  FULU_FORK_VERSION: "0x70{{ ethereum_genesis_fork_version_suffix }}"
  SKIP_RELAY_SIGNATURE_CHECK: "1"

mev_boost_container_command:
  - -addr=0.0.0.0:{{ mev_boost_server_port }}
  - -relay-check
  - -relays=http://0xa55c1285d84ba83a5ad26420cd5ad3091e49c55a813eee651cd467db38a8c8e63192f47955e9376f6b42f6d190571cb5@mev-relay-1.{{ network_server_subdomain }}:9062

ethereum_node_mev_boost_enabled: true
