name: Terraform lint
on:
  pull_request:
    paths:
      - 'terraform/**'
      - '.tool-versions'
      - '.github/actions/**'
      - '.github/workflows/lint-terraform.yaml'
  push:
    branches:
      - master
    paths:
      - 'terraform/**'
      - '.tool-versions'
      - '.github/actions/**'
      - '.github/workflows/lint-terraform.yaml'

jobs:
  terraform-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - uses: ./.github/actions/setup
      - name: Lint
        working-directory: ./terraform
        run: >
          terraform fmt --recursive --check --list=true --diff
